# Generated by Django 5.0.7 on 2024-07-24 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("activate", models.BooleanField(default=False)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parceiro",
                "verbose_name_plural": "Parceiros",
            },
        ),
    ]
