# Generated by Django 5.0.7 on 2024-07-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
