# Generated by Django 5.0.7 on 2024-07-24 08:14

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Royalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sales.order"),
                ),
            ],
            options={
                "verbose_name": "Remessa Royalty",
                "verbose_name_plural": "Remessas de royalty",
            },
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
                ),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sales.order"),
                ),
            ],
            options={
                "verbose_name": "Remessa Envio",
                "verbose_name_plural": "Remessas de envios",
            },
        ),
    ]
