# Generated by Django 5.0.7 on 2024-07-24 08:01

import uuid

import django.db.models.deletion
import django.utils.timezone
import src.apps.sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Agente",
                "verbose_name_plural": "Agentes",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Código de Venda",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("canceled", models.BooleanField(default=False)),
                ("pay", models.BooleanField(default=False)),
                (
                    "agent",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="sales.agent"),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "PENDING"), (1, "CANCELED"), (2, "PAID")],
                        default=src.apps.sales.models.CommissionStatus["PENDING"],
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sales.agent"),
                ),
                (
                    "order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sales.order"),
                ),
            ],
            options={
                "verbose_name": "Comissão",
                "verbose_name_plural": "Comissões",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ean", models.CharField(max_length=13)),
                ("description", models.TextField(blank=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "PHYSICAL"), (2, "VIDEO"), (3, "BOOK")],
                        default=src.apps.sales.models.ProductType["PHYSICAL"],
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="sales.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pedido",
                "verbose_name_plural": "Itens de Pedido",
            },
        ),
    ]
